project:
  type: website

execute:
  freeze: true

website:
  title: "Random Bytes"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/phihung
      - icon: twitter
        href: https://x.com/hunglp
  comments:
    giscus:
      repo: phihung/blog

format:
  html:
    theme: cosmo
    css: styles.css
