[project]
name = "blog"
version = "0.0.4"
requires-python = ">=3.11"
dependencies = [
    "jupyter>=1.1.1",
    "pyyaml",
    "ruff>=0.6.4",
]

[project.scripts]

[tool.ruff]
line-length = 100
target-version = "py311"

[tool.pytest.ini_options]
addopts = ""
